name: CI

on:
  push:
    branches:
      - '*'

jobs:
  in-docker_test:
    name: Docker tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache de deps
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Tests with Coverage
        run: mvn clean test site

      - name: Upload Test Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Test-Artifact
          path: ./target/site/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}